package JamSessionAutomate;

import java.awt.Color;
import java.io.File;
import java.net.URI;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.*;
import java.util.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jcontreras
 */
public class UploadInstrument extends javax.swing.JFrame {
    private String[] chords = {"C Major","C# Major","D Major","D# Major","E Major","F Major","F# Major","G Major","G# Major","A Major","A# Major","B Major",
        "C Minor","C# Minor","D Minor","D# Minor","E Minor","F Minor","F# Minor","G Minor","G# Minor","A Minor","A# Minor","B Minor"};
    private HashMap<String, String> map = new HashMap<String, String>();
    

    /**
     * Creates new form UploadInstrument
     */
    public UploadInstrument() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbbxInstrumentType = new javax.swing.JComboBox<>();
        txtVariation = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCmaj = new javax.swing.JButton();
        btnCsmaj = new javax.swing.JButton();
        btnDmaj = new javax.swing.JButton();
        btnDsmaj = new javax.swing.JButton();
        btnEmaj = new javax.swing.JButton();
        btnFmaj = new javax.swing.JButton();
        btnFsmaj = new javax.swing.JButton();
        btnGmaj = new javax.swing.JButton();
        lblCmaj = new javax.swing.JLabel();
        btnGsmaj = new javax.swing.JButton();
        lblCsmaj = new javax.swing.JLabel();
        btnAmaj = new javax.swing.JButton();
        lblDmaj = new javax.swing.JLabel();
        btnAsmaj = new javax.swing.JButton();
        lblDsmaj = new javax.swing.JLabel();
        lblEmaj = new javax.swing.JLabel();
        lblFmaj = new javax.swing.JLabel();
        lblFsmaj = new javax.swing.JLabel();
        lblGmaj = new javax.swing.JLabel();
        lblGsmaj = new javax.swing.JLabel();
        lblAmaj = new javax.swing.JLabel();
        lblAsmaj = new javax.swing.JLabel();
        lblBmaj = new javax.swing.JLabel();
        btnBmaj = new javax.swing.JButton();
        btnCmin = new javax.swing.JButton();
        lblCmin = new javax.swing.JLabel();
        btnCsmin = new javax.swing.JButton();
        lblCsmin = new javax.swing.JLabel();
        btnDmin = new javax.swing.JButton();
        lblDmin = new javax.swing.JLabel();
        btnDsmin = new javax.swing.JButton();
        lblDsmin = new javax.swing.JLabel();
        btnEmin = new javax.swing.JButton();
        lblEmin = new javax.swing.JLabel();
        btnFmin = new javax.swing.JButton();
        lblFmin = new javax.swing.JLabel();
        btnFsmin = new javax.swing.JButton();
        lblFsmin = new javax.swing.JLabel();
        btnGmin = new javax.swing.JButton();
        lblGmin = new javax.swing.JLabel();
        btnGsmin = new javax.swing.JButton();
        lblGsmin = new javax.swing.JLabel();
        btnAmin = new javax.swing.JButton();
        lblAmin = new javax.swing.JLabel();
        btnAsmin = new javax.swing.JButton();
        lblAsmin = new javax.swing.JLabel();
        btnBmin = new javax.swing.JButton();
        lblBmin = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Shonar Bangla", 1, 36)); // NOI18N
        jLabel1.setText("Upload Variation");

        cmbbxInstrumentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bass", "guitar", "keyz" }));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnCmaj.setText("C Major");
        btnCmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmajActionPerformed(evt);
            }
        });

        btnCsmaj.setText("C# Major");
        btnCsmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsmajActionPerformed(evt);
            }
        });

        btnDmaj.setText("D Major");
        btnDmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDmajActionPerformed(evt);
            }
        });

        btnDsmaj.setText("D# Major");
        btnDsmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsmajActionPerformed(evt);
            }
        });

        btnEmaj.setText("E Major");
        btnEmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmajActionPerformed(evt);
            }
        });

        btnFmaj.setText("F Major");
        btnFmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFmajActionPerformed(evt);
            }
        });

        btnFsmaj.setText("F# Major");
        btnFsmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFsmajActionPerformed(evt);
            }
        });

        btnGmaj.setText("G Major");
        btnGmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGmajActionPerformed(evt);
            }
        });

        lblCmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblCmaj.setText("No File Chosen.");

        btnGsmaj.setText("G# Major");
        btnGsmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGsmajActionPerformed(evt);
            }
        });

        lblCsmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblCsmaj.setText("No File Chosen.");

        btnAmaj.setText("A Major");
        btnAmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmajActionPerformed(evt);
            }
        });

        lblDmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblDmaj.setText("No File Chosen.");

        btnAsmaj.setText("A# Major");
        btnAsmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsmajActionPerformed(evt);
            }
        });

        lblDsmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblDsmaj.setText("No File Chosen.");

        lblEmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblEmaj.setText("No File Chosen.");

        lblFmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblFmaj.setText("No File Chosen.");

        lblFsmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblFsmaj.setText("No File Chosen.");

        lblGmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblGmaj.setText("No File Chosen.");

        lblGsmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblGsmaj.setText("No File Chosen.");

        lblAmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblAmaj.setText("No File Chosen.");

        lblAsmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblAsmaj.setText("No File Chosen.");

        lblBmaj.setForeground(new java.awt.Color(255, 0, 0));
        lblBmaj.setText("No File Chosen.");

        btnBmaj.setText("B Major");
        btnBmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBmajActionPerformed(evt);
            }
        });

        btnCmin.setText("C Minor");
        btnCmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCminActionPerformed(evt);
            }
        });

        lblCmin.setForeground(new java.awt.Color(255, 0, 0));
        lblCmin.setText("No File Chosen.");

        btnCsmin.setText("C# Minor");
        btnCsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsminActionPerformed(evt);
            }
        });

        lblCsmin.setForeground(new java.awt.Color(255, 0, 0));
        lblCsmin.setText("No File Chosen.");

        btnDmin.setText("D Minor");
        btnDmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDminActionPerformed(evt);
            }
        });

        lblDmin.setForeground(new java.awt.Color(255, 0, 0));
        lblDmin.setText("No File Chosen.");

        btnDsmin.setText("D# Minor");
        btnDsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsminActionPerformed(evt);
            }
        });

        lblDsmin.setForeground(new java.awt.Color(255, 0, 0));
        lblDsmin.setText("No File Chosen.");

        btnEmin.setText("E Minor");
        btnEmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEminActionPerformed(evt);
            }
        });

        lblEmin.setForeground(new java.awt.Color(255, 0, 0));
        lblEmin.setText("No File Chosen.");

        btnFmin.setText("F Minor");
        btnFmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFminActionPerformed(evt);
            }
        });

        lblFmin.setForeground(new java.awt.Color(255, 0, 0));
        lblFmin.setText("No File Chosen.");

        btnFsmin.setText("F# Minor");
        btnFsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFsminActionPerformed(evt);
            }
        });

        lblFsmin.setForeground(new java.awt.Color(255, 0, 0));
        lblFsmin.setText("No File Chosen.");

        btnGmin.setText("G Minor");
        btnGmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGminActionPerformed(evt);
            }
        });

        lblGmin.setForeground(new java.awt.Color(255, 0, 0));
        lblGmin.setText("No File Chosen.");

        btnGsmin.setText("G# Minor");
        btnGsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGsminActionPerformed(evt);
            }
        });

        lblGsmin.setForeground(new java.awt.Color(255, 0, 0));
        lblGsmin.setText("No File Chosen.");

        btnAmin.setText("A Minor");
        btnAmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAminActionPerformed(evt);
            }
        });

        lblAmin.setForeground(new java.awt.Color(255, 0, 0));
        lblAmin.setText("No File Chosen.");

        btnAsmin.setText("A# Minor");
        btnAsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsminActionPerformed(evt);
            }
        });

        lblAsmin.setForeground(new java.awt.Color(255, 0, 0));
        lblAsmin.setText("No File Chosen.");

        btnBmin.setText("B Minor");
        btnBmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBminActionPerformed(evt);
            }
        });

        lblBmin.setForeground(new java.awt.Color(255, 0, 0));
        lblBmin.setText("No File Chosen.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCsmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDsmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGsmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFsmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGmaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsmaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBmaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBmaj)
                    .addComponent(lblAsmaj)
                    .addComponent(lblEmaj)
                    .addComponent(lblFmaj)
                    .addComponent(lblFsmaj)
                    .addComponent(lblGmaj)
                    .addComponent(lblGsmaj)
                    .addComponent(lblAmaj)
                    .addComponent(lblDsmaj)
                    .addComponent(lblCsmaj)
                    .addComponent(lblCmaj)
                    .addComponent(lblDmaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCsmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDsmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGsmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFsmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBmin)
                    .addComponent(lblAsmin)
                    .addComponent(lblEmin)
                    .addComponent(lblFmin)
                    .addComponent(lblFsmin)
                    .addComponent(lblGmin)
                    .addComponent(lblGsmin)
                    .addComponent(lblAmin)
                    .addComponent(lblDsmin)
                    .addComponent(lblCsmin)
                    .addComponent(lblCmin)
                    .addComponent(lblDmin))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCmin)
                            .addComponent(lblCmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCsmin)
                            .addComponent(lblCsmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDmin)
                            .addComponent(lblDmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDsmin)
                            .addComponent(btnDsmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmin)
                            .addComponent(lblEmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFmin)
                            .addComponent(lblFmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFsmin)
                            .addComponent(lblFsmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGmin)
                            .addComponent(lblGmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGsmin)
                            .addComponent(lblGsmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAmin)
                            .addComponent(lblAmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAsmin)
                            .addComponent(lblAsmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBmin)
                            .addComponent(lblBmin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCmaj)
                            .addComponent(lblCmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCsmaj)
                            .addComponent(lblCsmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDmaj)
                            .addComponent(lblDmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDsmaj)
                            .addComponent(btnDsmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmaj)
                            .addComponent(lblEmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFmaj)
                            .addComponent(lblFmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFsmaj)
                            .addComponent(lblFsmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGmaj)
                            .addComponent(lblGmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGsmaj)
                            .addComponent(lblGsmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAmaj)
                            .addComponent(lblAmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAsmaj)
                            .addComponent(lblAsmaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBmaj)
                            .addComponent(btnBmaj))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        jLabel2.setText("Variation name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cmbbxInstrumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVariation, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbxInstrumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVariation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsminActionPerformed
        map.put("D# Minor", openFile(lblDsmin));
        System.out.println(map.get("D# Minor"));
    }//GEN-LAST:event_btnDsminActionPerformed

    private void btnDminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDminActionPerformed
        map.put("D Minor", openFile(lblDmin));
        System.out.println(map.get("D Minor"));
    }//GEN-LAST:event_btnDminActionPerformed

    private void btnCmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmajActionPerformed
        map.put("C Major", openFile(lblCmaj));
        System.out.println(map.get("C Major"));
    }//GEN-LAST:event_btnCmajActionPerformed

    private void btnCsmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsmajActionPerformed
        map.put("C# Major", openFile(lblCsmaj));
        System.out.println(map.get("C# Major"));
    }//GEN-LAST:event_btnCsmajActionPerformed

    private void btnDmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDmajActionPerformed
        map.put("D Major", openFile(lblDmaj));
        System.out.println(map.get("D Major"));
    }//GEN-LAST:event_btnDmajActionPerformed

    private void btnDsmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsmajActionPerformed
        map.put("D# Major", openFile(lblDsmaj));
        System.out.println(map.get("D# Major"));
    }//GEN-LAST:event_btnDsmajActionPerformed

    private void btnEmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmajActionPerformed
        map.put("E Major", openFile(lblEmaj));
        System.out.println(map.get("E Major"));
    }//GEN-LAST:event_btnEmajActionPerformed

    private void btnFmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFmajActionPerformed
        map.put("F Major", openFile(lblFmaj));
        System.out.println(map.get("F Major"));
    }//GEN-LAST:event_btnFmajActionPerformed

    private void btnFsmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFsmajActionPerformed
        map.put("F# Major", openFile(lblFsmaj));
        System.out.println(map.get("F# Major"));
    }//GEN-LAST:event_btnFsmajActionPerformed

    private void btnGmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGmajActionPerformed
        map.put("G Major", openFile(lblGmaj));
        System.out.println(map.get("G Major"));
    }//GEN-LAST:event_btnGmajActionPerformed

    private void btnGsmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGsmajActionPerformed
        map.put("G# Major", openFile(lblGsmaj));
        System.out.println(map.get("G# Major"));
    }//GEN-LAST:event_btnGsmajActionPerformed

    private void btnAmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmajActionPerformed
        map.put("A Major", openFile(lblAmaj));
        System.out.println(map.get("A Major"));
    }//GEN-LAST:event_btnAmajActionPerformed

    private void btnAsmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsmajActionPerformed
        map.put("A# Major", openFile(lblAsmaj));
        System.out.println(map.get("A# Major"));
    }//GEN-LAST:event_btnAsmajActionPerformed

    private void btnBmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBmajActionPerformed
        map.put("B Major", openFile(lblBmaj));
        System.out.println(map.get("B Major"));
    }//GEN-LAST:event_btnBmajActionPerformed

    private void btnCminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCminActionPerformed
        map.put("C Minor", openFile(lblCmin));
        System.out.println(map.get("C Minor"));
    }//GEN-LAST:event_btnCminActionPerformed

    private void btnCsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsminActionPerformed
        map.put("C# Minor", openFile(lblCsmin));
        System.out.println(map.get("C# Minor"));
    }//GEN-LAST:event_btnCsminActionPerformed

    private void btnEminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEminActionPerformed
        map.put("E Minor", openFile(lblEmin));
        System.out.println(map.get("E Minor"));
    }//GEN-LAST:event_btnEminActionPerformed

    private void btnFminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFminActionPerformed
        map.put("F Minor", openFile(lblFmin));
        System.out.println(map.get("F Minor"));
    }//GEN-LAST:event_btnFminActionPerformed

    private void btnFsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFsminActionPerformed
        map.put("F# Minor", openFile(lblFsmin));
        System.out.println(map.get("F# Minor"));
    }//GEN-LAST:event_btnFsminActionPerformed

    private void btnGminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGminActionPerformed
        map.put("G Minor", openFile(lblGmin));
        System.out.println(map.get("G Minor"));
    }//GEN-LAST:event_btnGminActionPerformed

    private void btnGsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGsminActionPerformed
        map.put("G# Minor", openFile(lblGsmin));
        System.out.println(map.get("G# Minor"));
    }//GEN-LAST:event_btnGsminActionPerformed

    private void btnAminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAminActionPerformed
        map.put("A Minor", openFile(lblAmin));
        System.out.println(map.get("A Minor"));
    }//GEN-LAST:event_btnAminActionPerformed

    private void btnAsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsminActionPerformed
        map.put("A# Minor", openFile(lblAsmin));
        System.out.println(map.get("A# Minor"));
    }//GEN-LAST:event_btnAsminActionPerformed

    private void btnBminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBminActionPerformed
        map.put("B Minor", openFile(lblBmin));
        System.out.println(map.get("B Minor"));
    }//GEN-LAST:event_btnBminActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        for(String s : chords){
            map.put(s,null);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //System.out.println(Arrays.toString(map.values().toArray()));
        //System.out.println(Arrays.toString(map.keySet().toArray()));
        String fileName;
        File sourceFile;
        Path sourcePath;
        File destinationDirectory;
        File destinationFile;
        if(!map.containsValue(null)&& !txtVariation.getText().equals("")){
            
            destinationDirectory = new File("Audio/"+cmbbxInstrumentType.getSelectedItem().toString()+"/"+txtVariation.getText());
            destinationDirectory.mkdirs();
            
            for(String chord: chords){
                fileName = txtVariation.getText()+"_"+chord;
                sourceFile = new File(map.get(chord));
                sourcePath = sourceFile.toPath();
                destinationFile = new File("Audio/"+cmbbxInstrumentType.getSelectedItem().toString()+"/"+txtVariation.getText()+"/"+fileName+".wav");
                try{
                    Files.copy(sourcePath, destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                }
                catch(Exception e){
                    System.out.println("Unable to copy");
                }
                //cmbbxInstrumentType.getSelectedItem().toString()
            }
            System.out.println("Success");
        }
        else{
            System.out.println("Missing Files");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadInstrument().setVisible(true);
            }
        });
    }
    
    //opens file chooser and returns string of chosen file
    private String openFile(JLabel lbl){
        JButton open = new JButton();
        JFileChooser jfc = new JFileChooser(); 
        //makes the open action do something??
        if(jfc.showOpenDialog(open) == JFileChooser.APPROVE_OPTION) { 
             
        }
        //Label next to button is set to filename
        lbl.setText(jfc.getSelectedFile().getName());
        lbl.setForeground(Color.GREEN);
        return jfc.getSelectedFile().getAbsolutePath();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmaj;
    private javax.swing.JButton btnAmin;
    private javax.swing.JButton btnAsmaj;
    private javax.swing.JButton btnAsmin;
    private javax.swing.JButton btnBmaj;
    private javax.swing.JButton btnBmin;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCmaj;
    private javax.swing.JButton btnCmin;
    private javax.swing.JButton btnCsmaj;
    private javax.swing.JButton btnCsmin;
    private javax.swing.JButton btnDmaj;
    private javax.swing.JButton btnDmin;
    private javax.swing.JButton btnDsmaj;
    private javax.swing.JButton btnDsmin;
    private javax.swing.JButton btnEmaj;
    private javax.swing.JButton btnEmin;
    private javax.swing.JButton btnFmaj;
    private javax.swing.JButton btnFmin;
    private javax.swing.JButton btnFsmaj;
    private javax.swing.JButton btnFsmin;
    private javax.swing.JButton btnGmaj;
    private javax.swing.JButton btnGmin;
    private javax.swing.JButton btnGsmaj;
    private javax.swing.JButton btnGsmin;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbbxInstrumentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmaj;
    private javax.swing.JLabel lblAmin;
    private javax.swing.JLabel lblAsmaj;
    private javax.swing.JLabel lblAsmin;
    private javax.swing.JLabel lblBmaj;
    private javax.swing.JLabel lblBmin;
    private javax.swing.JLabel lblCmaj;
    private javax.swing.JLabel lblCmin;
    private javax.swing.JLabel lblCsmaj;
    private javax.swing.JLabel lblCsmin;
    private javax.swing.JLabel lblDmaj;
    private javax.swing.JLabel lblDmin;
    private javax.swing.JLabel lblDsmaj;
    private javax.swing.JLabel lblDsmin;
    private javax.swing.JLabel lblEmaj;
    private javax.swing.JLabel lblEmin;
    private javax.swing.JLabel lblFmaj;
    private javax.swing.JLabel lblFmin;
    private javax.swing.JLabel lblFsmaj;
    private javax.swing.JLabel lblFsmin;
    private javax.swing.JLabel lblGmaj;
    private javax.swing.JLabel lblGmin;
    private javax.swing.JLabel lblGsmaj;
    private javax.swing.JLabel lblGsmin;
    private javax.swing.JTextField txtVariation;
    // End of variables declaration//GEN-END:variables
}
